DROP TABLE "PNOTE_COMMENT";
DROP TABLE "CLIENT_INFO";
DROP TABLE "CLIENT";
DROP TABLE "CHART";
DROP TABLE "HEALTH_CHART";
DROP TABLE "PATIENT";
DROP TABLE "STAFF";


CREATE TABLE "CHART" (
	"CHART_ID"	VARCHAR2(10)		NOT NULL,
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL,
    "PTITLE"       VARCHAR2(120)	NOT NULL,
	"PNOTE"	VARCHAR2(4000)		NOT NULL,
	"STAFF_ID"	VARCHAR2(7)		NOT NULL
);

COMMENT ON COLUMN "CHART"."CHART_ID" IS 'YYMMDD00';

COMMENT ON COLUMN "CHART"."PATIENT_ID" IS 'YYMM0000';
COMMENT ON COLUMN "CHART"."PTITLE" IS '제목';
COMMENT ON COLUMN "CHART"."PNOTE" IS '환자 재활치료 내용';

COMMENT ON COLUMN "CHART"."STAFF_ID" IS 'YY00001 / YY00002 /';


CREATE TABLE "PATIENT" (
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL,
	"PATIENT_NAME"	VARCHAR2(50)		NOT NULL,
	"PATIENT_AGE"	NUMBER		NOT NULL,
	"PATIENT_GENDER"	CHAR(1)		NOT NULL,
	"PATIENT_DISEASE"	VARCHAR2(20)		NULL,
	"PATIENT_ADDRESS"	VARCHAR2(100)		NULL,
	"PATIENT_NO"	VARCHAR2(13)		NOT NULL
);

COMMENT ON COLUMN "PATIENT"."PATIENT_ID" IS 'YYMM0000';

COMMENT ON COLUMN "PATIENT"."PATIENT_NAME" IS '환자이름';

COMMENT ON COLUMN "PATIENT"."PATIENT_AGE" IS '환자 나이';

COMMENT ON COLUMN "PATIENT"."PATIENT_GENDER" IS '환자 성별 0이면 남자 1이면 여자';

COMMENT ON COLUMN "PATIENT"."PATIENT_DISEASE" IS '환자 질병분류';

COMMENT ON COLUMN "PATIENT"."PATIENT_ADDRESS" IS '환자 주소';

COMMENT ON COLUMN "PATIENT"."PATIENT_NO" IS '환자 주민번호';



CREATE TABLE "CLIENT_INFO" (
	"CLIENT_NUM"	NUMBER(2)	DEFAULT 1	NOT NULL,
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL,
	"CLIENT_NAME"	VARCHAR2(20)		NOT NULL,
	"CLIENT_PHONE"	NUMBER		NOT NULL,
	"FAMILY"	VARCHAR2(10)		NOT NULL,
	"CLIENT_ADDRESS"	VARCHAR2(100)		NULL,
	"CLIENT_NO"	VARCHAR2(13)		NOT NULL
);

COMMENT ON COLUMN "CLIENT_INFO"."CLIENT_NUM" IS '환자의보호자우선순위';

COMMENT ON COLUMN "CLIENT_INFO"."PATIENT_ID" IS 'YYMM0000';

COMMENT ON COLUMN "CLIENT_INFO"."CLIENT_NAME" IS '보호자이름';

COMMENT ON COLUMN "CLIENT_INFO"."CLIENT_PHONE" IS '보호자 전화번호';

COMMENT ON COLUMN "CLIENT_INFO"."FAMILY" IS '입원 환자와 가족관계';

COMMENT ON COLUMN "CLIENT_INFO"."CLIENT_ADDRESS" IS '보호자 주소';

COMMENT ON COLUMN "CLIENT_INFO"."CLIENT_NO" IS '보호자 주민번호';



CREATE TABLE "STAFF" (
	"STAFF_ID"	VARCHAR2(7)		NOT NULL,
	"STAFF_NAME"	VARCHAR2(10)		NOT NULL,
	"STAFF_PWD"	VARCHAR2(6)		NOT NULL,
	"STAFF_EMAIL"	VARCHAR2(100)		NOT NULL,
	"STAFF_TYPE"	CHAR(2)	DEFAULT 2	NOT NULL
);

COMMENT ON COLUMN "STAFF"."STAFF_ID" IS 'YY00001 / YY00002 /';

COMMENT ON COLUMN "STAFF"."STAFF_NAME" IS '작성자의 이름입력';

COMMENT ON COLUMN "STAFF"."STAFF_PWD" IS '비밀번호(숫자4자권장,영문자)';

COMMENT ON COLUMN "STAFF"."STAFF_EMAIL" IS '이메일';

COMMENT ON COLUMN "STAFF"."STAFF_TYPE" IS '의사(10), 간호사(20), 치료사(30),행정(40)';



CREATE TABLE "PNOTE_COMMENT" (
	"CHART_ID"	VARCHAR2(10)		NOT NULL,
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL,
	"PNOTE_REPLAY"	VARCHAR2(4000)		NOT NULL,
	"PNOTE_REP"	VARCHAR2(4000)		NULL
);

COMMENT ON COLUMN "PNOTE_COMMENT"."CHART_ID" IS 'YYMMDD00';

COMMENT ON COLUMN "PNOTE_COMMENT"."PATIENT_ID" IS 'YYMM0000';

COMMENT ON COLUMN "PNOTE_COMMENT"."PNOTE_REPLAY" IS '차드에보호자질문';

COMMENT ON COLUMN "PNOTE_COMMENT"."PNOTE_REP" IS '스태프의답글';



CREATE TABLE "CLIENT" (
	"CLIENT_ID"	VARCHAR2(20)		NOT NULL,
	"CLIENT_PWD"	VARCHAR2(20)		NOT NULL,
	"CLIENT_EMAIL"	VARCHAR2(100)		NOT NULL,
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "CLIENT"."CLIENT_ID" IS '웹사이트사용자아이디';

COMMENT ON COLUMN "CLIENT"."CLIENT_PWD" IS '보호자 비밀번호';

COMMENT ON COLUMN "CLIENT"."CLIENT_EMAIL" IS '보호자 이메일- 비번찾기용';

COMMENT ON COLUMN "CLIENT"."PATIENT_ID" IS 'YYMM0000';



CREATE TABLE "HEALTH_CHART" (
	"CHART_ID"	VARCHAR2(10)		NOT NULL,
	"PATIENT_ID"	VARCHAR2(10)		NOT NULL,
	"PULSE"	NUMBER		NULL,
	"WEIGHT"	NUMBER		NULL,
	"BLOOD_PRESSURE"	NUMBER		NULL,
	"PEE"	NUMBER		NULL,
	"COMMENT"	VARCHAR2(4000)		NULL,
	"STAFF_ID"	VARCHAR2(7)		NOT NULL
);

COMMENT ON COLUMN "HEALTH_CHART"."CHART_ID" IS 'YYMMDD00';

COMMENT ON COLUMN "HEALTH_CHART"."PATIENT_ID" IS 'YYMM0000';

COMMENT ON COLUMN "HEALTH_CHART"."PULSE" IS '맥박 수';

COMMENT ON COLUMN "HEALTH_CHART"."WEIGHT" IS '체중';

COMMENT ON COLUMN "HEALTH_CHART"."BLOOD_PRESSURE" IS '혈압';

COMMENT ON COLUMN "HEALTH_CHART"."PEE" IS '소변 양 또는 횟수';

COMMENT ON COLUMN "HEALTH_CHART"."COMMENT" IS '환자 입원 건강 특이사항';

COMMENT ON COLUMN "HEALTH_CHART"."STAFF_ID" IS 'YY00001 / YY00002 /';

ALTER TABLE "CHART" ADD CONSTRAINT "PK_CHART" PRIMARY KEY (
	"CHART_ID",
	"PATIENT_ID"
);

ALTER TABLE "PATIENT" ADD CONSTRAINT "PK_PATIENT" PRIMARY KEY (
	"PATIENT_ID"
);

ALTER TABLE "CLIENT_INFO" ADD CONSTRAINT "PK_CLIENT_INFO" PRIMARY KEY (
	"CLIENT_NUM",
	"PATIENT_ID"
);

ALTER TABLE "STAFF" ADD CONSTRAINT "PK_STAFF" PRIMARY KEY (
	"STAFF_ID"
);

ALTER TABLE "PNOTE_COMMENT" ADD CONSTRAINT "PK_PNOTE_COMMENT" PRIMARY KEY (
	"CHART_ID",
	"PATIENT_ID"
);

ALTER TABLE "CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY (
	"CLIENT_ID"
);

ALTER TABLE "HEALTH_CHART" ADD CONSTRAINT "PK_HEALTH_CHART" PRIMARY KEY (
	"CHART_ID",
	"PATIENT_ID"
);

ALTER TABLE "CHART" ADD CONSTRAINT "FK_PATIENT_TO_CHART_1" FOREIGN KEY (
	"PATIENT_ID"
)
REFERENCES "PATIENT" (
	"PATIENT_ID"
);

ALTER TABLE "CHART" ADD CONSTRAINT "FK_STAFF_TO_CHART_1" FOREIGN KEY (
	"STAFF_ID"
)
REFERENCES "STAFF" (
	"STAFF_ID"
);

ALTER TABLE "CLIENT_INFO" ADD CONSTRAINT "FK_PATIENT_TO_CLIENT_INFO_1" FOREIGN KEY (
	"PATIENT_ID"
)
REFERENCES "PATIENT" (
	"PATIENT_ID"
);

ALTER TABLE "PNOTE_COMMENT" ADD CONSTRAINT "FK_CHART_TO_PNOTE_COMMENT_1" FOREIGN KEY (
	"CHART_ID",
    "PATIENT_ID"
)
REFERENCES "CHART" (
	"CHART_ID",
    "PATIENT_ID"
);


ALTER TABLE "CLIENT" ADD CONSTRAINT "FK_PATIENT_TO_CLIENT_1" FOREIGN KEY (
	"PATIENT_ID"
)
REFERENCES "PATIENT" (
	"PATIENT_ID"
);

ALTER TABLE "HEALTH_CHART" ADD CONSTRAINT "FK_PATIENT_TO_HEALTH_CHART_1" FOREIGN KEY (
	"PATIENT_ID"
)
REFERENCES "PATIENT" (
	"PATIENT_ID"
);

ALTER TABLE "HEALTH_CHART" ADD CONSTRAINT "FK_STAFF_TO_HEALTH_CHART_1" FOREIGN KEY (
	"STAFF_ID"
)
REFERENCES "STAFF" (
	"STAFF_ID"
);

alter table health_chart rename column "COMMENT" to memo;

commit